### ISSUE TITLE
返回有问题

### ISSUE THREAD

**Issue by CCCCXcode** [cdpenggod/CDPVideoPlayer#3]
如果视频的url  有问题这边就不能返回了  全部是黑色的了

**Comment by cdpenggod** [comment]
问题已解决：原因是url资源系统不识别，不兼容，监听状态返回fail，内部会调用closePlayer方法清空子view和子layer，所以没有返回键，可以用代理监听播放状态，fail后生成自定义UI返回，或者更改里面源代码（不推荐，毕竟太麻烦）
